package vu.lt.mybatis.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMMENT.ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private Integer id;
    private Post post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMMENT.NAME
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMMENT.TEXT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMMENT.POST_ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private Integer postId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMMENT.ID
     *
     * @return the value of PUBLIC.COMMENT.ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMMENT.ID
     *
     * @param id the value for PUBLIC.COMMENT.ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMMENT.NAME
     *
     * @return the value of PUBLIC.COMMENT.NAME
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMMENT.NAME
     *
     * @param name the value for PUBLIC.COMMENT.NAME
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMMENT.TEXT
     *
     * @return the value of PUBLIC.COMMENT.TEXT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMMENT.TEXT
     *
     * @param text the value for PUBLIC.COMMENT.TEXT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMMENT.POST_ID
     *
     * @return the value of PUBLIC.COMMENT.POST_ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMMENT.POST_ID
     *
     * @param postId the value for PUBLIC.COMMENT.POST_ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
}