package vu.lt.mybatis.model;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.CREATED_ON
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.TEXT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.TITLE
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.ID
     *
     * @return the value of PUBLIC.POST.ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.ID
     *
     * @param id the value for PUBLIC.POST.ID
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.CREATED_ON
     *
     * @return the value of PUBLIC.POST.CREATED_ON
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.CREATED_ON
     *
     * @param createdOn the value for PUBLIC.POST.CREATED_ON
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.TEXT
     *
     * @return the value of PUBLIC.POST.TEXT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.TEXT
     *
     * @param text the value for PUBLIC.POST.TEXT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.TITLE
     *
     * @return the value of PUBLIC.POST.TITLE
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.TITLE
     *
     * @param title the value for PUBLIC.POST.TITLE
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}