package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Comment;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENT
     *
     * @mbg.generated Sun May 01 15:16:32 EEST 2022
     */
    int updateByPrimaryKey(Comment record);
}